env: "TREX"

env_args:
  key: null
  time_limit: 100
  pretrained_wrapper: null
  n_agents: 0
  TREX_config: CLI_agent_testig
  TREX_path: C:/source/TREX-Core/TREX_Core/

test_greedy: True
test_nepisode: 100
test_interval: 50000
log_interval: 50000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
