exclude: null
grid-search:

  "--config":
    - "ia2c_lbf_coop"

  hidden_dim:
    - 128
    - 64

  lr:
    - 0.0001
    - 0.0003
    - 0.0005

  standardise_rewards:
    - True
    - False
# network type
  use_rnn:
    - True
    - False


#  evaluation_epsilon:
#    - 0.05
#    - 0.0
#
#  epsilon_anneal_time:
#    - 50000
#    - 200000

  target_update_interval_or_tau:
    - 0.01
    - 200

  entropy_coef:
    - 0.01
    - 0.001

  q_nstep:
    - 5
    - 10


  t_max:
    - 2050000
  test_nepisode:
    - 100
  test_interval:
    - 25000
  log_interval:
    - 25000
  save_model_interval:
    - 50000
  save_model:
    - false

grid-search-groups:
  env0:
    - "--env-config": "gymcoop"
    - env_args.key: 'Foraging-8x8-2p-2f-coop-v0'
    - env_args.time_limit: 25
